from fastapi import APIRouter, Depends, HTTPException, status
from src.api.v1.schemas import (
    AnalyzeDecisionRequest,
    ExecutiveDecisionBrief,
    ExperimentAuditRequest,
    ExperimentAuditResponse,
    CalibrationRequest,
    CalibrationResponse
)
from src.api.dependencies import (
    get_mede_workflow,
    get_experiment_auditor,
    get_bayesian_calibrator
)
from src.agents.graph import MEDEAgentWorkflow
from src.tools.experimentation import ExperimentAuditor
from src.tools.bayesian_calibrator import BayesianLiftCalibrator

router = APIRouter()

@router.post("/analyze", response_model=ExecutiveDecisionBrief, status_code=status.HTTP_200_OK)
def analyze_decision(
    request: AnalyzeDecisionRequest,
    workflow: MEDEAgentWorkflow = Depends(get_mede_workflow)
) -> ExecutiveDecisionBrief:
    try:
        # Initialize graph state
        state = {
            "raw_user_query": request.query,
            "target_channels": request.target_channels or [],
            "messages": [],
            "extracted_parameters": {
                "total_budget_eur": request.total_budget_eur
            } if request.total_budget_eur else {}
        }
        
        # Invoke LangGraph application
        result = workflow.invoke(state)
        
        # Extract and return the final brief generated by SynthesizerNode
        final_brief = result.get("final_brief")
        if not final_brief:
            raise HTTPException(status_code=500, detail="Failed to generate decision brief.")
            
        return ExecutiveDecisionBrief(**final_brief)
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/audit-experiment", response_model=ExperimentAuditResponse, status_code=status.HTTP_200_OK)
def audit_experiment(
    request: ExperimentAuditRequest,
    auditor: ExperimentAuditor = Depends(get_experiment_auditor)
) -> ExperimentAuditResponse:
    try:
        # 1. Check for Sample Ratio Mismatch (SRM)
        srm_result = auditor.audit_sample_ratio_mismatch(
            observed_control=request.control_traffic,
            observed_variant=request.variant_traffic,
            expected_control_ratio=request.planned_control_ratio,
            alpha=request.alpha
        )
        
        # 2. Check statistical power
        baseline_p = request.control_conversions / request.control_traffic
        variant_p = request.variant_conversions / request.variant_traffic
        
        # Prevent division by zero if baseline is 0
        relative_lift = ((variant_p - baseline_p) / baseline_p) if baseline_p > 0 else 0.0
        
        sample_size_per_arm = int((request.control_traffic + request.variant_traffic) / 2)
        power_result = auditor.calculate_statistical_power(
            sample_size_per_arm=sample_size_per_arm,
            baseline_p=baseline_p,
            relative_lift=relative_lift,
            alpha=request.alpha
        )
        
        # 3. Assemble Verdict
        srm_detected = srm_result["srm_detected"]
        is_powered = not power_result["is_underpowered"]
        
        if srm_detected:
            verdict = f"INVALID TEST: Severe Sample Ratio Mismatch detected (p={srm_result['p_value']:.4f}). Do not use these results."
        elif not is_powered:
            verdict = f"INVALID TEST: Underpowered test. Current power is {power_result['power']:.2%} (target 80%)."
        else:
            verdict = "VALID TEST: No SRM detected and test is adequately powered."
            
        return ExperimentAuditResponse(
            srm_detected=srm_detected,
            srm_p_value=srm_result["p_value"],
            chi2_stat=srm_result["chi2_stat"],
            is_valid_test=(not srm_detected and is_powered),
            statistical_power=power_result["power"],
            verdict=verdict
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/calibrate", response_model=CalibrationResponse, status_code=status.HTTP_200_OK)
def calibrate_channel(
    request: CalibrationRequest,
    calibrator: BayesianLiftCalibrator = Depends(get_bayesian_calibrator)
) -> CalibrationResponse:
    try:
        result = calibrator.calibrate_channel_prior(
            prior_mean=request.mmm_prior_mean,
            prior_sd=request.mmm_prior_sd,
            lift_estimate=request.experiment_lift_mean,
            lift_se=request.experiment_lift_se
        )
        
        return CalibrationResponse(
            channel=request.channel,
            original_prior_mean=request.mmm_prior_mean,
            calibrated_posterior_mean=result["posterior_mean"],
            calibrated_posterior_sd=result["posterior_sd"],
            hdi_95=result["hdi_95"],
            shrinkage_factor=result["shrinkage_factor"],
            executive_takeaway=f"MMM prior for {request.channel} updated from {request.mmm_prior_mean} to {result['posterior_mean']:.4f}."
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
